# Generated by Django 3.2.25 on 2025-02-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('focus_area', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('workoutplan_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('day1_focus_area', models.CharField(blank=True, help_text='like chest,back etc.', max_length=100, null=True)),
                ('day2_focus_area', models.CharField(blank=True, help_text='like chest,back etc.', max_length=100, null=True)),
                ('day3_focus_area', models.CharField(blank=True, help_text='like chest,back etc.', max_length=100, null=True)),
                ('day4_focus_area', models.CharField(blank=True, help_text='like chest,back etc.', max_length=100, null=True)),
                ('day5_focus_area', models.CharField(blank=True, help_text='like chest,back etc.', max_length=100, null=True)),
                ('day6_focus_area', models.CharField(blank=True, help_text='like chest,back etc.', max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='Account.member')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('workoutexercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6')])),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(default=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exercise.exercise')),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='Exercise.workoutplan')),
            ],
        ),
    ]
