# Generated by Django 3.2.25 on 2025-02-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0002_rename_workout_plan_workoutexercise_workoutplan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='workoutplan_id',
            new_name='workoutplan',
        ),
    ]
