[phases.setup]
nixPkgs = ["nodejs", "python311"]

[phases.build]
cmds = [
  "cd NewFitnessPoint/GMS_FRONTEND && npm install && npm run build",
  "python -m venv /tmp/venv",
  "source /tmp/venv/bin/activate && cd NewFitnessPoint && pip install -r requirements.txt",
  "source /tmp/venv/bin/activate && cd NewFitnessPoint && python manage.py collectstatic --noinput"
]

[start]
cmd = "source /tmp/venv/bin/activate && cd NewFitnessPoint && gunicorn NewFitnessPoint.wsgi:application --bind 0.0.0.0:$PORT"