# Generated by Django 4.1.13 on 2025-01-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dateofbirth', models.DateField(default='2023-01-01')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('occupation', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('address', models.TextField()),
                ('pincode', models.CharField(default='387001', max_length=6)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberMedicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('heart_conditions', models.TextField(blank=True, null=True)),
                ('orthopedic_conditions', models.TextField(blank=True, null=True)),
                ('other_conditions', models.TextField(blank=True, null=True)),
                ('bmi_report_image', models.ImageField(blank=True, help_text='Upload a BMI report image (optional).', null=True, upload_to='bmi_reports/')),
                ('diet_chart_image', models.ImageField(blank=True, help_text='Upload a diet chart image (optional).', null=True, upload_to='diet_charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.member')),
            ],
        ),
    ]
