# Generated by Django 3.2.25 on 2025-02-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('experience', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
