# Generated by Django 5.1.6 on 2025-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, default='None', editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='password',
            field=models.CharField(blank=True, default='None', editable=False, max_length=255, null=True),
        ),
    ]
