# Generated by Django 4.1.13 on 2025-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='photo',
            new_name='AboutUs_photo',
        ),
        migrations.AddField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(default=1, help_text='Upload a profile photo', upload_to='ownerphoto/'),
            preserve_default=False,
        ),
    ]
