# Generated by Django 5.1.6 on 2025-02-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_info',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_profile_photo',
            field=models.ImageField(default=1, help_text='Upload a profile photo', upload_to='trainer_photo/'),
            preserve_default=False,
        ),
    ]
