# Generated by Django 3.2.25 on 2025-02-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_trainer_trainer_info_trainer_trainer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='dateofbirth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='dateofbirth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
