# Generated by Django 4.1.13 on 2025-02-07 05:34

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_member_joining_date_member_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joining_date',
            field=models.DateField(default=Account.models.Member.get_tomorrow),
        ),
        migrations.AlterField(
            model_name='owner',
            name='AboutUs_photo',
            field=models.ImageField(help_text='Upload a AboutUs photo', upload_to='media/ownerphoto/aboutUS_img'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(help_text='Upload a profile photo', upload_to='media/ownerphoto/'),
        ),
    ]
