# Generated by Django 5.1.6 on 2025-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20250221_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Upload a gallery image', upload_to='gallery/')),
            ],
        ),
    ]
