# Generated by Django 4.1.13 on 2025-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_member_joining_date_alter_owner_aboutus_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='AboutUs_photo',
            field=models.ImageField(help_text='Upload a AboutUs photo', upload_to='ownerphoto/aboutUS_img'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(help_text='Upload a profile photo', upload_to='ownerphoto/'),
        ),
    ]
