# Generated by Django 5.1.6 on 2025-03-13 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_owner_facebooklink_owner_instagramlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Upload a gallery image', max_length=255, verbose_name='image'),
        ),
    ]
