# Generated by Django 5.1.6 on 2025-03-14 11:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_membermedicaldetails_bmi_report_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_profile_photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload a profile photo', max_length=255, verbose_name='image/trainer_photo/'),
        ),
    ]
