# Generated by Django 5.1.6 on 2025-03-14 12:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_trainer_trainer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='AboutUs_photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload a AboutUs photo', max_length=255, verbose_name='owner_AboutUs'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_profile_photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload a profile photo', max_length=255, verbose_name='image'),
        ),
    ]
