# Generated by Django 5.1.6 on 2025-03-14 12:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_owner_aboutus_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermedicaldetails',
            name='bmi_report_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a BMI report image (optional).', max_length=255, null=True, verbose_name='bmi_reports'),
        ),
        migrations.AlterField(
            model_name='membermedicaldetails',
            name='diet_chart_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a diet chart image (optional).', max_length=255, null=True, verbose_name='diet_charts'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='AboutUs_photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload a AboutUs photo', max_length=255, verbose_name='owner AboutUs image'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='heroimage',
            field=cloudinary.models.CloudinaryField(help_text='Upload a Hero Image', max_length=255, verbose_name='hero_section Image'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload a profile photo', max_length=255, verbose_name='owner photo'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_profile_photo',
            field=cloudinary.models.CloudinaryField(help_text='Upload a profile photo', max_length=255, verbose_name='trainer profile photo'),
        ),
    ]
