# Generated by Django 5.1.6 on 2025-03-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_membermedicaldetails_bmi_report_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='password',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
