# Generated by Django 5.1.6 on 2025-03-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='Account.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.trainer')),
            ],
        ),
    ]
