# Generated by Django 5.1.6 on 2025-02-20 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0003_trainer_trainer_info_trainer_trainer_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(blank=True, to='Account.member')),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.trainer')),
            ],
        ),
    ]
