# Generated by Django 5.1.6 on 2025-02-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_training',
            old_name='trainer_name',
            new_name='trainer',
        ),
    ]
