# Generated by Django 5.1.6 on 2025-03-28 10:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='AllMemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=7)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.trainer')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.memberattendance')),
            ],
        ),
    ]
