# Generated by Django 3.2.25 on 2025-02-27 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0004_auto_20250221_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='AllMemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=7)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.memberattendance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.member')),
            ],
        ),
    ]
