# Generated by Django 5.1.6 on 2025-03-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmemberattendance',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.trainer'),
        ),
    ]
