# Generated by Django 5.1.4 on 2025-03-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_remove_memberattendance_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberattendance',
            name='trainer',
        ),
    ]
