# Generated by Django 5.1.6 on 2025-03-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_remove_memberattendance_trainer_and_more'),
    ]

    operations = [
    ]
