# Generated by Django 5.1.6 on 2025-03-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_remove_memberattendance_trainer'),
    ]

    operations = [
       
    ]
